---
title: "p8105_hw5_yy3421"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 10, 
  fig.height = 8,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem 1

### Description of the raw data

```{r}
homicide_data_raw = read_csv("data/homicide-data.csv")
```

The raw dataset contains `r homicide_data_raw |> nrow()` observations and `r homicide_data_raw |> ncol()` variables.

```{r}
homicide_data = 
  homicide_data_raw |> 
  mutate(
    city_state = paste(city, state, sep = ", ")
  ) 
```

```{r total number of homicides}
total_homicides = 
  homicide_data |> 
  group_by(city_state) |> 
  summarise(total_number_of_homicides = n()) 
```

```{r number of unsolved homicide}
unsolved_homicide = 
  homicide_data |> 
  group_by(city_state) |> 
  filter(
    disposition %in% c("Closed without arrest", "Open/No arrest")
  ) |> 
  summarise(number_of_unsolved_homicides = n()) 
```

## Prop test for Baltimore
```{r}
output_Baltimore = vector("list", length = 3)

Baltimore_total = 
  total_homicides |> 
  filter(
    city_state == "Baltimore, MD"
  ) 

Baltimore_unsolved = 
  unsolved_homicide |> 
  filter(
    city_state == "Baltimore, MD"
  ) 
    
prop_Balt = prop.test(1825, 2827, alternative = "two.sided") |> broom::tidy()

```

## Problem 2
```{r data cleaning and tidying}
files_collection = 
  tibble(
    file_name = list.files(path = "./data/problem_2"),
    file_path = paste(c("./data/problem_2/"), file_name, sep = "")
  ) |>
  mutate(
    data = map(file_path, read_csv)
  ) |> 
  separate(file_name, into = c("control_arm", "subject_ID"), sep = "_") |> 
  separate(subject_ID, into = c("subject_ID", "file_type"), sep = "\\.")|> 
  unnest(data) |> 
  pivot_longer(
    week_1:week_8,
    names_to = c("week"),
    values_to = c("data") 
  ) |> 
  separate(week, into = c("week", "time"), sep = "_")|> 
  select(
    -file_type, -file_path, -week
  ) |> 
  mutate(
    time = as.numeric(time)
  )
```

Making plot:
```{r plot}
files_collection |> 
  ggplot(aes(x = time, y = data, color = subject_ID))+
  geom_line()+
  facet_grid(~control_arm)
```

## Problem 3

```{r}

output = vector("list", 5000)

sim_mean_sd = function(mu, n = 30, sigma = 5) {
  
  sim_data = tibble(
    x = rnorm(n = 30, mean = mu, sd = sigma),
  )
  
  sim_data |> 
    t.test(conf.level = 0.95) |> 
    broom::tidy() |> 
    select(
      estimate, p.value
    )
    
}

```

```{r}
for (i in 1:100) {
  output[[i]] = sim_mean_sd(mu=0)
}

sim_results = bind_rows(output)
```

